### ISSUE TITLE
Fails too Install in LO Version: 6.1.3.2 (x64)

### ISSUE THREAD

**Issue by JD4x4** [vmiklos/ged2dot#10]
Fails to install under Version: 6.1.3.2 (x64) with the following error:

(com.sun.star.uno.RuntimeException) { { Message = "<class 'FileNotFoundError'>: [Errno 2] No such file or directory: 'C:\\\\Users\\\\JD4x4\\\\AppData\\\\Roaming\\\\LibreOffice\\\\4\\\\user\\\\uno_packages\\\\cache\\\\uno_packages\\\\lu124763pzkbq.tmp_\\\\gedcom-0.7%20(for%20Draw).oxt\\\\loader.py', traceback follows\X000a  File \"C:\\Program Files\\LibreOffice\\program\\pythonloader.py\", line 149, in writeRegistryInfo\X000a    mod = self.getModuleFromUrl( locationUrl )\X000a  File \"C:\\Program Files\\LibreOffice\\program\\pythonloader.py\", line 94, in getModuleFromUrl\X000a    fileHandle = open( filename, encoding='utf_8' )\X000a\X000a", Context = (com.sun.star.uno.XInterface) @0 } }

**Comment by vmiklos** [comment]
Confirmed, broken on Linux as well with 6.1. I plan to take a look.

**Comment by vmiklos** [comment]
https://github.com/vmiklos/ged2dot/commit/c653c53e65581871a7ee148e47b261578ecece7a fixes the extension for me, can you test and report back if that was the problem on Windows as well? I only tested on Liniux so far.

OXT if you have trouble "building" that from source:

https://github.com/vmiklos/ged2dot/releases/download/0.8/gedcom-0.8.oxt
