### ISSUE TITLE
Uses wrong path (win10)

### ISSUE THREAD

**Issue by tracton** [vmiklos/ged2dot#11]
In gedcom-0.7.oxt\filter.py the os.environ(PROGRAMFILES) settings returns "Program Files" but the default graphviz installer puts the file at "Program Files (x86)".  So dot.exe is never found.  Suggestions:
- tell the user about the issue (don't make them find a log file)
- search both paths
- update the extension to work in libreoffice 6, where it does not even write to a log file.

**Comment by vmiklos** [comment]
Right, the only config I tested was a 32bit Windows VM, so it's not surprising that 64bitness breaks things. So you say graphviz is 32bit, your Windows is 64bit, what is the bitness of LibreOffice?

Agreed, best to search in both paths.

Please test 0.8 (see releases here on GitHub), it is meant to fix compat problems with newer LibreOffice.

I'll try to reproduce this 32bit graphviz thing on 64bit Windows, I don't expect it's too hard to fix this.

**Comment by vmiklos** [comment]
https://github.com/vmiklos/ged2dot/commit/bdcf19b30ce1f44bd111adfa9514bf3f2e6cb865 fixes this.
