### ISSUE TITLE
messy interconnects; how to clean up?

### ISSUE THREAD

**Issue by tracton** [vmiklos/ged2dot#12]
The attached image shows:
1) multiple connections between 2 people
2) a tangled mess where a simpler connection would be possible.

Is there a way to indicate (in the visual output) where improper connections might be found in the GEDCOM file, so users can edit it manually, like a line number or node number?  Editing the graphics in Draw is unusually difficult for me, due to overlapping lines.

![libreoffice ged2dot filter mess](https://user-images.githubusercontent.com/19613613/56443630-891c7880-62c3-11e9-8143-4ececfc1ab6a.PNG)

![libreoffice ged2dot filter mess 2](https://user-images.githubusercontent.com/19613613/56443688-b23d0900-62c3-11e9-94cc-e3c62dc88b49.PNG)

**Comment by vmiklos** [comment]
Can you provide your gedcom file and your ged2dotrc (or a description of what options you picked in the GUI)? I assume you will want to anonymize it first.

If you want a quick workaround: try to reduce the scope of the nodes you want to layout, infinite amount of nodes are not possible to lay out in general sadly. (The graph has to be a planar graph, see https://en.wikipedia.org/wiki/Planar_graph for details.)

But who knows, perhaps your specific problem is more about ged2dot is lame, and it's not about a theoretical limit. :-)

**Comment by tracton** [comment]
Thanks for your help!
May I just send/email you a GED file instead of putting it into Github?  Then I won't have to figure out how to anonymize 300 people.

ged2dotrc is all defaults.

I can reproduce the mess when setting the GUI "Number of generations to show" to 2.  Using '1', it's clean (almost... there's a couple of stray connection ovals that you were prob'ly using for debuggery).

There IS a loop -- my grandparents were first cousins. Their common ancestor is in the file but it's not in the first 2 generations from the selected root family.  I may just edit the GED file to see if that's the cause.

**Comment by vmiklos** [comment]
It's not ideal, but sure, if you are not able to anonimize your .ged input then you can send it to me (see git log for the email address). I just prefer the reporter to do the boring homework of minimal self-contained testcase creation. :-)

**Comment by vmiklos** [comment]
Haven't got a reproducer in a month, closing.
