### ISSUE TITLE
gv graphing errors

### ISSUE THREAD

**Issue by dougstarfish** [vmiklos/ged2dot#15]
After finally figuring out I had a lack of sex for an ancestor in the .ged file (PR submitted to allow identification of such issues and also to check for lack of config file and to give some better error messages), I have a problem with the outputed dot syntax.. Any clues what's going on here? It's not immediately obvious to me, and it happens very early. It seems to be a problem with Lefty understanding the file, so dotty fails. But the file doesn't look so unusual to me, and I've done a fair bit of graphviz stuff in the past:

$ dotty hughes.gv 
graph parser: syntax error near line 1
context: igraph >>>  { <<< 
dotty.lefty: cannot load graph

Here are the first 10 lines:
digraph {
splines = ortho
subgraph Depth5 {
rank = same
P1133 [ shape = box,
label = <<table border="0" cellborder="0"><tr><td><img src="/home/doug/git/ged2dot/placeholder-m.png"/></td></tr><tr><td>John<br/>Durland<br/>1767-1800</td></tr></table>>,
color = blue ]
P1134 [ shape = box,
label = <<table border="0" cellborder="0"><tr><td><img src="/home/doug/git/ged2dot/placeholder-f.png"/></td></tr><tr><td>Cynthia<br/>Ruggles<br/>1774-1803</td></tr></table>>,
color = pink ]

#  dotty -V
dotty version 96c (09-24-96)
lefty version 10 Mar 2005
graphviz version 2.30.1 (20180420.1509)

**Comment by vmiklos** [comment]
Do you have a minimal reproducer .ged input for the problematic .dot output?

**Comment by dougstarfish** [comment]
Interestingly, I can display it (ugly though, no names - maybe a config issue) at http://www.webgraphviz.com/, with just 3 generations and 600 linues

I get the same error with 1 generation (depth) and 113 lines in the file. It gives me 3 generations instead of just 1 (though I guess arguably it's just 2 since it's the family (plus parents and children) and their parents. 
I still get basically the same error.

**Comment by dougstarfish** [comment]
I found the error. If the graph is not named, then dotty/lefty will give an error.

so the normal output is digraph {
but graphviz/dotty is expecting digraph Tree {

(where tree is some tree/graph name)

Since this does not appear to present a general problem for graphviz, any objection to me submitting a pull request with a name put in there? I also have a thought on a default ged2dotrc that is good for Ancestry and creating the graphs on Linux. (no images)

**Comment by vmiklos** [comment]
> any objection to me submitting a pull request with a name put in there?

No, not at all.

> I also have a thought on a default ged2dotrc

My hope was that creating a default one on `make`, but having it as an untracked file so `git diff` is clean is good enough, but you could definitely put together other configs as well -- ideal would be to have sample .ged for it as well, and then you could have a test for it, like we have `test_screenshot()` already.

**Comment by vmiklos** [comment]
I assume you fixed this on master now?

**Comment by dougstarfish** [comment]
I added a ged2dot.sample in the last commit. It seems pretty reasonable and useful to help somebody get started with dotty or other tools
