### ISSUE TITLE
Smaller bugs and visual improvements

### ISSUE THREAD

**Issue by humaita-github** [vmiklos/ged2dot#170]
Hi,

first let me start by saying that this is an amazing project. While using it, I found smaller bugs, and I am also proposing visual improvements. 

Here are the small bugs I found:

1) When creating a PDF from your dot files (i.e. dot -Tpdf ...) the images will be horizontally stretched as the boxes get wider. You can fix that by adding "scale=true" to the image tags. No negative impact when generating other formats, e.g. dot -Tpng ...

2) When creating a SVG from your dot files (i.e. dot -Tsvg ...), the SVG will only work in the directory you created it, because paths are hardcoded. So I recommend using relative path. (You also need to adapt "image_dir", I didn't to that in my patch as I didn't need it)

3) When creating a SVG from your dot files, the text will not be properly centered. This is due to the fact that dot might assume another font when generating the SVG than the program viewing the SVG. To fix this just add "FONT FACE=Times" to any text being displayed. No negative impact when generating other formats.

Here are three improvements I suggest:

4) Years are always displayed in the form "YYYY-YYYY", even if one of the years is missing. I would suggest having "*YYYY" or "&dagger; YYYY" if only one year is available. I didn't create a patch for this.

5) When printing large posters of the family trees, the PNG images don't look very good. I created SVG ones, feel free to include them. However, creating PNG (i.e. dot -Tpng ...) might not work out of the box in some distributions if the images are SVG, so you might consider having a command line option to switch between PNG and SVG. In my patch I just hard coded it.

6) I think that using "splines = spline" looks better than using "splines = ortho", especially if you add a wedding symbol. Maybe you want to add this as an option in the command line? Here is how one of the test cases looks like:

<a href="https://ibb.co/6bXTM3d"><img src="https://i.ibb.co/6bXTM3d/screenshot-new.png" alt="screenshot-new" border="0"></a>

Below you can find my patch that covers 80% of these topics, and the respective SVG. I didn't find a way of uploading "marriage.png", but you can easily convert the SVG to PNG yourself.

===== PATCH =====
<pre>
--- ged2dot.old.py	2021-06-06 17:52:20.800000000 +0200
+++ ged2dot.new.py	2021-06-12 08:21:55.660000000 +0200
@@ -258,10 +258,10 @@
                 sex = self.get_sex().lower()
             else:
                 sex = 'u'
-            image_path = get_abspath("placeholder-%s.png" % sex)
+            image_path = ("placeholder-%s.svg" % sex)
         label = "&lttable border=\"0\" cellborder=\"0\"&gt&lttr&gt&lttd&gt"
-        label += "&ltimg src=\"" + image_path + "\"/&gt"
-        label += "&lt/td&gt&lt/tr&gt&lttr&gt&lttd&gt"
+        label += "&ltimg scale=\"true\" src=\"" + image_path + "\"/&gt"
+        label += "&lt/td&gt&lt/tr&gt&lttr&gt&lttd&gt&ltFONT FACE=\"Times\"&gt"
         if name_order == "big":
             # Big endian: family name first.
             label += self.get_surname() + "&ltbr/&gt"
@@ -271,7 +271,7 @@
             label += self.get_forename() + "&ltbr/&gt"
             label += self.get_surname() + "&ltbr/&gt"
         label += self.get_config().get_birth() + "-" + self.get_config().get_death()
-        label += "&lt/td&gt&lt/tr&gt&lt/table&gt"
+        label += "&lt/FONT&gt&lt/td&gt&lt/tr&gt&lt/table&gt"
         return label
 
     def get_color(self) -&gt str:
@@ -518,7 +518,7 @@
         for node in self.subgraph:
             if not isinstance(node, Family):
                 continue
-            stream.write(to_bytes(node.get_identifier() + " [shape=point, width=0.1];\n"))
+            stream.write(to_bytes(node.get_identifier() + " [shape=circle, margin=\"0,0\", label=&lt&lttable border=\"0\" cellborder=\"0\"&gt&lttr&gt&lttd&gt&ltimg src=\"./marriage.svg\"/&gt&lt/td&gt&lt/tr&gt&lt/table&gt&gt];\n"))
         stream.write(to_bytes("\n"))
 
     def __store_edges(self, stream: BinaryIO) -&gt None:
@@ -527,13 +527,13 @@
                 continue
             family = node
             if family.wife:
-                from_wife = family.wife.get_identifier() + " -&gt " + family.get_identifier() + " [dir=none];\n"
+                from_wife = family.wife.get_identifier() + ":s -&gt " + family.get_identifier() + ":c [dir=none];\n"
                 stream.write(to_bytes(from_wife))
             if family.husb:
-                from_husb = family.husb.get_identifier() + " -&gt " + family.get_identifier() + " [dir=none];\n"
+                from_husb = family.husb.get_identifier() + ":s -&gt " + family.get_identifier() + ":c [dir=none];\n"
                 stream.write(to_bytes(from_husb))
             for child in family.child_list:
-                stream.write(to_bytes(family.get_identifier() + " -&gt " + child.get_identifier() + " [dir=none];\n"))
+                stream.write(to_bytes(family.get_identifier() + ":c -&gt " + child.get_identifier() + ":n [dir=none];\n"))
 
     def store(self, subgraph: List[Node], config: Dict[str, str]) -&gt None:
         """Exports subgraph to a graphviz path."""
@@ -548,7 +548,7 @@
         stream.write(to_bytes("// Generated by &lthttps://github.com/vmiklos/ged2dot&gt.\n"))
         stream.write(to_bytes("digraph\n"))
         stream.write(to_bytes("{\n"))
-        stream.write(to_bytes("splines = ortho;\n"))
+        stream.write(to_bytes("splines = spline;\n"))
         stream.write(to_bytes("\n"))
 
         self.subgraph = subgraph
</pre>

===== marriage.svg =====
<pre>
&lt?xml version="1.0" encoding="utf-8"?&gt
&lt!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20010904//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd"&gt
&ltsvg version="1.0" xmlns="http://www.w3.org/2000/svg" width="32px" height="23px" viewBox="0 0 526 382" preserveAspectRatio="xMidYMid meet"&gt
 &ltg fill="#333333"&gt
  &ltpath d="M160 360.9 c-28.6 -2.7 -60.1 -14.4 -82.9 -30.7 -32.1 -22.9 -56.9 -61.1 -64.5 -99.2 -4.9 -24.6 -4.7 -54.7 0.4 -79.7 8.9 -43.1 38.1 -83.3 77.1 -106.1 4.6 -2.7 10 -5.5 11.9 -6.2 1.9 -0.7 4 -1.7 4.6 -2.2 2 -1.5 17.7 -7 27 -9.4 14.4 -3.7 29.1 -5.4 47.8 -5.4 28.2 0 48 3.9 71.3 13.7 l8.2 3.5 7.8 -3.2 c10 -4.3 24.3 -8.6 36.3 -11.1 13.7 -2.9 48.2 -3.7 63.9 -1.5 57.1 8.1 102.9 40.6 128.4 91.2 4.4 8.7 11.1 28.4 13.1 38.4 7.5 37.5 3.2 80.5 -10.9 111.7 -4.3 9.4 -13.3 24.7 -17.9 30.4 -11.3 13.8 -17 20 -25.6 27.1 -26.5 22.2 -58.8 35.5 -94 38.7 -35.2 3.3 -68.2 -1.3 -93.9 -13.1 l-6.4 -2.9 -8.1 3.4 c-27.3 11.7 -58.8 15.9 -93.6 12.6z m40.7 -62.6 c2.3 -0.8 2.2 -0.9 -2.2 -6.8 -6.1 -8.2 -16.6 -29 -20.4 -40.5 -11.4 -35 -11.6 -82.1 -0.5 -116.4 3.9 -11.8 12.3 -29.2 19.2 -39.5 l6 -8.9 -5.6 -1.1 c-8.8 -1.8 -25.2 -1.3 -36.2 0.9 -43.4 8.8 -77 42.3 -85.3 85 -4.8 24.1 -1.9 45.6 9.2 68.5 14.8 30.7 43.7 52.3 78.8 59 8.3 1.6 32.7 1.4 37 -0.2z m155.6 0.6 c34.5 -5.1 65.8 -27.2 80.8 -57.1 15.6 -31 16.5 -62 2.8 -94.1 -11.2 -26.4 -37.3 -49.6 -66.2 -58.8 -14.6 -4.7 -35.4 -6.3 -48 -3.8 -5.5 1.1 -6.8 2.1 -4.7 3.4 1.3 0.8 7.3 10.2 12.2 19 9.1 16.3 15.4 35 18.4 54.5 2.2 14.4 2.2 45.8 0 60.3 -4 25.8 -14 50.6 -27.9 69.5 -2.1 3 -3.6 5.6 -3.2 6 2 2 24.9 2.8 35.8 1.1z m-89 -42.1 c9.1 -12.3 14.9 -24.5 19.4 -40.8 2.6 -9.6 2.5 -37.6 -0.1 -48 -4 -15.7 -13.2 -33.9 -22.9 -45.4 l-2.5 -2.8 -4.1 5.2 c-28.2 35.7 -30.9 86.3 -6.6 124.6 3.7 5.9 10.3 14.4 11 14.4 0.3 0 2.9 -3.3 5.8 -7.2z"/&gt
 &lt/g&gt
 &ltg fill="#ffffff"&gt
  &ltpath d="M0 191 l0 -191 263 0 263 0 0 191 0 191 -263 0 -263 0 0 -191z m201 167 c19.3 -2.1 37.2 -6.9 52.6 -14 l8 -3.7 6 2.9 c43.2 21.1 102.5 20.8 148.9 -0.7 24.7 -11.4 41.7 -25.3 62.1 -50.4 8.6 -10.7 19.1 -31.1 24.2 -47.2 15 -47.2 8.9 -100.8 -16.1 -140.9 -27.1 -43.3 -68.9 -70.2 -120.8 -77.6 -14.2 -2 -43.1 -1.5 -55.9 1.1 -15.2 2.9 -35.6 9.6 -45.5 14.7 -2.7 1.5 -3.3 1.4 -10.9 -1.9 -24.8 -10.7 -46.1 -15.2 -72.2 -15.3 -15.7 0 -31.2 1.9 -44.8 5.4 -9.3 2.4 -25 7.9 -27 9.4 -0.6 0.5 -2.7 1.5 -4.6 2.2 -1.9 0.7 -7.3 3.5 -11.9 6.2 -39 22.8 -68.2 63 -77.1 106.1 -12.2 59.4 4.4 116.9 45.5 157.2 26.2 25.7 64.2 43 101.5 46.4 13.9 1.2 27.9 1.3 38 0.1z"/&gt
  &ltpath d="M160.7 301.5 c-20 -3.8 -38.8 -12.9 -54 -26.1 -28.8 -25 -42.2 -67.1 -34.1 -107.4 8.7 -43.1 41.9 -76.1 85.7 -85.1 8.7 -1.8 12.6 -2 26.2 -1.6 8.8 0.3 18.1 1 20.7 1.7 l4.8 1.2 -4.3 5.6 c-10.1 13.1 -19.8 31.7 -25.1 47.8 -10.9 33.4 -10.7 76.2 0.5 110.4 4.2 12.7 14.5 32.5 22.3 43 l6.3 8.5 -4.1 1.3 c-6.3 2.1 -35.3 2.5 -44.9 0.7z"/&gt
  &ltpath d="M324.5 302.3 c-3.5 -0.4 -11.5 -2.4 -11.5 -2.9 0 -0.1 2.6 -3.8 5.8 -8.1 15.7 -20.9 25.6 -45 29.8 -72 2.1 -14.1 2.1 -40.3 0 -54.3 -4.2 -27.6 -15.5 -54.3 -31.9 -75.4 -2.1 -2.7 -3.6 -5.1 -3.3 -5.3 1.5 -1.5 16.9 -3.3 28.2 -3.3 24.7 0 43.5 5.5 63.2 18.7 46.2 30.7 61.4 93.2 35.3 145.1 -15 29.9 -46.3 52 -80.8 57.1 -6.7 1 -28 1.3 -34.8 0.4z"/&gt
  &ltpath d="M253.6 261.3 c-13.2 -17.5 -20.5 -36.4 -22.5 -57.8 -1.1 -12.5 -0.1 -28.1 2.5 -39 3.9 -15.8 13.5 -34.8 22.9 -45.2 l5 -5.6 4.6 5.4 c15.1 17.7 24 39.2 25.8 62.9 2.3 28.3 -4.8 54.9 -20.2 76 -4.5 6.2 -9.7 12 -10.8 12 -0.4 0 -3.7 -3.9 -7.3 -8.7z"/&gt
 &lt/g&gt
&lt/svg&gt
</pre>

===== placeholder-f.svg =====
<pre>
&lt?xml version="1.0" encoding="utf-8"?&gt
&lt!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20010904//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd"&gt
&ltsvg version="1.0" xmlns="http://www.w3.org/2000/svg" width="100px" height="100px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid meet"&gt
 &ltg fill="#595959"&gt
  &ltpath d="M17.5 96.3 c-4.8 -1.2 -5.5 -2.9 -5.5 -14.6 0 -12.2 1.3 -16.3 6 -19.7 3.5 -2.5 8.8 -2.6 10.6 -0.2 1.2 1.5 1.3 1.5 1.4 -1 0 -3.2 2.4 -5.8 5.3 -5.8 1.2 0 2.8 -0.4 3.6 -0.9 0.8 -0.6 -0.6 -1.1 -4.4 -1.6 -13.8 -1.7 -19.5 -5 -19.5 -11.3 0 -4.7 0.7 -5.6 5 -7.4 5.2 -2.2 7 -4.9 8 -11.7 1.4 -10.2 6.1 -15.7 15.4 -18.2 7.8 -2.1 19.2 0.6 23.8 5.8 2.5 2.7 4.8 8.7 4.8 12.5 0 5 3.3 9.6 8.5 11.8 4.4 1.9 4.5 2.1 4.5 6.4 0 6.9 -2.7 8.9 -15.9 11.6 -4.7 0.9 -7.9 2 -7.1 2.2 0.8 0.3 2.9 0.9 4.5 1.4 2.4 0.8 3.1 1.6 3.6 4.4 0.4 2.7 0.7 3.1 1.3 1.8 1.1 -2.5 7.1 -2.3 10.7 0.3 5.2 3.7 6.4 7.2 6.4 19.2 0 10.7 0 10.9 -2.8 13.3 l-2.8 2.4 -31.7 -0.1 c-17.4 -0.1 -32.6 -0.4 -33.7 -0.6z"/&gt
 &lt/g&gt
 &ltg fill="#ffffff"&gt
  &ltpath d="M0 50 l0 -50 50 0 50 0 0 50 0 50 -50 0 -50 0 0 -50z m82.7 41.6 c2.6 -2.3 2.8 -2.9 2.7 -10.3 0 -8.9 -1.6 -12.9 -6.5 -16.4 -2.9 -2 -3.2 -2.1 -4.1 -0.5 -0.5 0.9 -2.3 3.3 -4 5.2 -10.4 11.8 -28.5 12.5 -39.7 1.6 -2.6 -2.6 -5.3 -5.6 -5.8 -6.6 -1 -1.9 -1.1 -1.9 -4.1 0.2 -4.5 3.3 -6.2 7.8 -6.2 16.9 0 8.4 1 10.5 5.5 11.6 1.1 0.2 14.9 0.5 30.7 0.6 l28.7 0.1 2.8 -2.4z m-26.6 -20.7 c4.8 -1.5 10.9 -6.5 10.9 -9 0 -1.9 -1.3 -2.7 -7.5 -4.5 -3.2 -1 -4.4 -3.7 -2.6 -5.8 0.7 -0.8 3.3 -1.7 5.9 -2 11.4 -1.6 19.2 -5.3 19.2 -9.2 0 -0.8 -2 -2.3 -4.5 -3.4 -5.2 -2.2 -8.5 -6.8 -8.5 -12 0 -11.1 -12.4 -20.8 -22.8 -18 -9.1 2.4 -13.8 8 -15.2 18.1 -1 6.9 -3.3 10.2 -8.6 11.9 -3.4 1.2 -4.7 3 -3.8 5.5 0.9 2.3 8.4 5.3 16.9 6.7 7.6 1.3 8 1.5 8.3 4.1 0.3 2.8 -1.1 3.9 -6.9 5.1 -5.3 1.1 -4.5 5.8 1.6 9.6 6.4 4 11.3 4.7 17.6 2.9z"/&gt
 &lt/g&gt
&lt/svg&gt
</pre>

===== placeholder-m.svg and placeholder-u.svg=====
<pre>
&lt?xml version="1.0" encoding="utf-8"?&gt
&lt!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20010904//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd"&gt
&ltsvg version="1.0" xmlns="http://www.w3.org/2000/svg" width="100px" height="100px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid meet"&gt
 &ltg fill="#595959"&gt
  &ltpath d="M17.4 96.3 c-4.9 -1 -5.6 -3.2 -5.2 -16 0.3 -10.6 0.6 -12.2 2.6 -14.8 4.5 -5.7 8.9 -7.9 22.5 -10.9 l2.9 -0.7 -3.7 -4.1 c-5.5 -6 -7.8 -12 -8.3 -21.4 -0.7 -12.3 2.1 -18.5 10 -22.5 8 -4.1 18.6 -3.5 25.9 1.4 10.6 7 10.8 29.3 0.3 41.8 -3.6 4.4 -3.6 5.9 0 5.9 7.4 0 18.1 5.8 21.9 11.9 2 3.2 2.2 4.7 2 14.6 -0.4 16.2 2.7 15 -36.6 15.1 -17.7 0.1 -33.2 0 -34.3 -0.3z"/&gt
 &lt/g&gt
 &ltg fill="#ffffff"&gt
  &ltpath d="M0 50 l0 -50 50 0 50 0 0 50 0 50 -50 0 -50 0 0 -50z m83 41.5 c3 -3.1 3.1 -17 0.1 -21.9 -3.9 -6.2 -10 -9.4 -23.8 -12.2 -4.1 -0.8 -3.9 -4.1 0.8 -9.6 13.9 -16.5 10.9 -36.2 -6.3 -40.8 -7.5 -2.1 -16.7 2.4 -20.6 10 -4.4 8.5 -1.6 21.3 6.7 30.3 4.4 4.7 5.2 8.1 2.4 9.5 -1 0.5 -4.6 1.5 -8 2.2 -6.7 1.4 -12.9 4.9 -16.5 9.5 -1.9 2.5 -2.4 4.4 -2.7 11.8 -0.3 9.5 0.7 12.1 5.3 13 1.1 0.3 15.3 0.4 31.3 0.3 27.9 -0.1 29.3 -0.2 31.3 -2.1z"/&gt
 &lt/g&gt
&lt/svg&gt
</pre>

**Comment by vmiklos** [comment]
Nice, glad you like ged2dot. Would you mind sending your patch as a pull request, so I can review it?

Thanks! :-)

**Comment by humaita-github** [comment]
Hi, 

thank you for the reply. Sorry, I dont know how to open a pull request. But I just noticed that I can upload/attach ZIP files. Below you can find the patch and the image files I mentioned. Regarding my points above, my patch should cover:

Proper fix for 
- (1) Horizontal stretch with PDFs
- (3) Text in SVGs not centered

Quick and dirty fix for 
- (2) Hard coded paths in SVG. You still need to adapt "image_dir", I didn't to that in my patch as I didn't need it. Also, it might make sense to have a command line option that toggles this together with the next point
- (5) Use SVG instead of PNG
- (6) Use "splines". It might make sense to have this as a command line option to chose either ortho or splines

Not addressed:
- (4) Different handling of years

[patch_and_images.zip](https://github.com/vmiklos/ged2dot/files/6644724/patch_and_images.zip)

**Comment by vmiklos** [comment]
OK, not a big problem, I can turn these into a pull request for you. How should I credit you? Normally you do `git config user.name "Foo Bar"` and `git config user.email a@b.c` and then you commit, finally submit the PR. Or should I not credit you?

**Comment by humaita-github** [comment]
Hi, thank you, you can credit me as "humaita". Best regards

**Comment by vmiklos** [comment]
Ok, I'm with limited connectivity this week, but I'll deal with this after that.

**Comment by vmiklos** [comment]
1 out of 6 done :-)

**Comment by vmiklos** [comment]
Regarding 2), ged2dot defaults to absolute paths as relative path break when you move the .dot file around, but no problem to have a switch that opts in for relative paths. Note that there is also an inlineize.py tool in this repo which turns the images inline, which makes it easy to e.g. mail around the generated svg.

**Comment by vmiklos** [comment]
> 4. Years are always displayed in the form "YYYY-YYYY", even if one of the years is missing. I would suggest having "*YYYY" or "† YYYY" if only one year is available. I didn't create a patch for this.

Hmm, so bare YYYY is a bit confusing, and e.g. ancestry.com also uses YYYY- to indicate that the death date is not known. But the "† YYYY" notation when only the death date is known makes sense, let me do that.

**Comment by humaita-github** [comment]
Hi, thank you. If its only the birthyear it should be „ * YYYY“, i.e. with an asterisk before the year.   That is a very common way of denoting the birth date, at least in Germany ;-)

**Comment by vmiklos** [comment]
I'm not comfortable with changing the default behavior, e.g. here (Hungary) the "* 1234" format is not familiar. But I just added an option for this, --birthformat '* {}' does what you requested.

**Comment by vmiklos** [comment]
> 5. When printing large posters of the family trees, the PNG images don't look very good. I created SVG ones, feel free to include them. However, creating PNG (i.e. dot -Tpng ...) might not work out of the box in some distributions if the images are SVG, so you might consider having a command line option to switch between PNG and SVG. In my patch I just hard coded it.

Let's try switching unconditionally, I can always re-introduce the .png variant later if somebody is not happy with it.

**Comment by vmiklos** [comment]
Alright, the above does 6) from your list to have the special icon for marriage. I didn't bother with splines=spline vs ortho, but if you keep finding that useful, please open a dedicated issue for it. And if you attach images to issues, it's best to insert them directly, so the link doesn't expire. :-)

Anyhow, plenty of great suggestions, thanks for the ideas. I'll cut a 7.2 release with these in it soon.
