### ISSUE TITLE
Show date of marriage

### ISSUE THREAD

**Issue by drzraf** [vmiklos/ged2dot#179]
There is now an icon but (optionally) showing the date of the marriage (if available) could be an interesting addition too.

**Comment by vmiklos** [comment]
Do you have a sample GEDCOM file that has such info?

**Comment by drzraf** [comment]
```
[...]
0 @F6@ FAM
1 MARR
2 DATE 04 NOV 1967
1 HUSB @I11@
1 WIFE @I12@
1 CHIL @I6@
0 @F18@ FAM
1 MARR
2 DATE 18 FEB 1946
1 HUSB @I33@
1 WIFE @I34@
1 CHIL @I35@
```

**Comment by vmiklos** [comment]
Thanks. One more question is how to present this. Do you have a suggested manually edited .dot file that shows the output you expect?

**Comment by drzraf** [comment]
No idea on my side. That may be a challenging to present this information in a clean way without cluttering the rest of the tree.

**Comment by drzraf** [comment]
![Screenshot from 2021-12-06 01-20-02](https://user-images.githubusercontent.com/1169926/144786619-23280836-73d9-4e5f-8e4d-4bd7be125ea8.png)
Within the circle, using a small font, could be suitable.
(Locality would another interesting element, but even more challenging to display)

**Comment by vmiklos** [comment]
I finally got around to fix the various CI problems (both Windows and macOS was broken, just Linux was working), so now can focus on this request.

I think the easiest is to just use the year number inside the circle instead of the marriage icon when the marriage date is non-empty.

**Comment by vmiklos** [comment]
It looks like this (random screenshot):

![image](https://user-images.githubusercontent.com/13838/145650435-04c29544-199a-492b-bbc5-77a22758c173.png)

**Comment by drzraf** [comment]
It's awesome!
It just misses circle label centering within the circle (in case it's easy to fix)
![Screenshot from 2021-12-12 22-52-22](https://user-images.githubusercontent.com/1169926/145740477-856a1e0a-5b60-4e11-bc79-1e5f15b1eff5.png)

**Comment by vmiklos** [comment]
Actually what I noticed now is that the marriage SVG is mis-positioned when the PNG output is used. But if I provide an explicit size for the SVG, then all is fine, let me fix that (and add a matching test).
