### ISSUE TITLE
General failure on many generations nor images are shown, with relative path

### ISSUE THREAD

**Issue by pacoriviere** [vmiklos/ged2dot#20]
I try to import a gedcom file with over 1500 families and 20 generations.
1) It always crashes with a "General failure. General input/ouput failure" message. Unless I choose less than 7 generations. Same file opens smoothingly on Android phone with FamilyGem version 0.7.12, http://www.familygem.app and https://github.com/michelesalvador/FamilyGem
Platform is Ubuntu GNU-Linux 18.04 LTS, LibreOffice 6.0.7.3, LibreOffice Draw GEDCOM import filter 0.7 and graphviz version 2.40.1-2
GEDCOM file version is 5.5.1 and was created by GRAMPS version 4.2.8. File size is 808kB
I tried both, first opening Draw and rigth-click the gedcom file and choose "Open with Draw". Same general failure message.
I tried to reproduce this with the following torture files from https://www.tamurajones.net/ but was not able to. Maybe this is related to the number of generations. These are large files with only 2 generations:
https://www.tamurajones.net/downloads/ThreeTortureTests1.5/Married1200.ged
https://www.tamurajones.net/downloads/Siblings0.1.5/Siblings1200.ged

2) Images are correctly referenced in gedcom file in the way "./MEDIA/imagefile.jpg".
gedcom file and MEDIA folder are in the same folder at opening, and FamilyGem opens over 700 images in a rush with same setup.
I guess this is related to the relative pathfile: "./whatever".

**Comment by vmiklos** [comment]
To begin with, please report one problem / issue, otherwise it's not clear when it is fixed :-)

Re the first problem: try to cut down your input .ged step by step, making sure it reproduces the problem after each step. Then replace sensitive data in the minimal reproducer with mock data, finally attach it here.

Re the second problem, please attach a reproducer for that as well, it sounds not too complicated to support custom image paths.

**Comment by vmiklos** [comment]
I've tested that the default options can open both files with current ge2dot master. As for your images, you need to place images of people with a filename "Givenname Familyname YYYY.jpg" in a directory, then use --imagedir to refer to that directory. If you use a relative path, it'll be relative to the GEDCOM file. So I guess, for now, there is nothing to fix here.
