### ISSUE TITLE
Ubuntu / LibreOffice 7.3.0.3 / Extension 7.3 / How to render images

### ISSUE THREAD

**Issue by johnjohndoe** [vmiklos/ged2dot#202]
**Context**
- I am trying to understand how I can render **images** in **LibreOffice** as shown in the screenshot in the _README.md_.
- I followed suggestions regarding the path and file names mentioned here: https://github.com/vmiklos/ged2dot/issues/20#issuecomment-753628096

**Environment**
- Ubuntu 20.04.3
- LibreOffice 7.3.0.3
- [Extension 7.3](https://github.com/vmiklos/ged2dot/releases/tag/v7.3)

**Folder structure**
```
├── export1.ged
└── Fotos
    ├── Jane Doe 2001.jpg
    └── John Doe 1966.jpg
```

**File content of export1.ged**
``` gedcom
0 HEAD
1 SOUR Gramps
2 VERS 5.1.5
2 NAME Gramps
1 DATE 16 FEB 2022
2 TIME 21:12:00
1 SUBM @SUBM@
1 FILE /home/john/Data/Privat/Stammbaumforschung/TestBilderAnzeigen/export1.ged
1 COPR Copyright (c) 2022 .
1 GEDC
2 VERS 5.5.1
2 FORM LINEAGE-LINKED
1 CHAR UTF-8
1 LANG English
0 @SUBM@ SUBM
1 NAME
0 @I0000@ INDI
1 NAME John /Doe/
2 GIVN John
2 SURN Doe
1 SEX M
1 BIRT
2 DATE 9 APR 1966
1 FAMS @F0000@
1 OBJE @O0001@
1 CHAN
2 DATE 16 FEB 2022
3 TIME 20:11:35
0 @I0001@ INDI
1 NAME Jane /Doe/
2 GIVN Jane
2 SURN Doe
1 SEX F
1 BIRT
2 DATE 23 APR 2001
1 FAMC @F0000@
2 PEDI birth
1 OBJE @O0000@
1 CHAN
2 DATE 16 FEB 2022
3 TIME 20:11:17
0 @F0000@ FAM
1 HUSB @I0000@
1 CHIL @I0001@
1 CHAN
2 DATE 16 FEB 2022
3 TIME 20:09:15
0 @O0000@ OBJE
1 FILE ./Fotos/Jane Doe 2001.jpg
2 FORM jpg
2 TITL Jane Doe 2001
1 CHAN
2 DATE 16 FEB 2022
3 TIME 20:11:15
0 @O0001@ OBJE
1 FILE ./Fotos/John Doe 1966.jpg
2 FORM jpg
2 TITL John Doe 1966
1 CHAN
2 DATE 16 FEB 2022
3 TIME 20:11:33
0 TRLR
```

**Reproducer steps**
1. Open LibreOffice
2. Select `export1.ged` via "File / Open ..."
3. Confirm default options in the dialog with "OK"

**Actual result**
- The rendering opens without images as shown here:
  ![image](https://user-images.githubusercontent.com/144518/154357766-20a72927-de9a-4036-b623-59581f2c4e6e.png)

**Expected behavior**
- The rendering opens with images.

**Comment by vmiklos** [comment]
Sorry for the slow answer.

This seems to work for me, but indeed the documentation is quite poor. To be more explicit, if I go to the test directory, then `soffice --nologo happy.ged` gives me the result from the screenshot. Commit coming in a bit to describe the expectations wrt the images.
