### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'chil'

### ISSUE THREAD

**Issue by furlongm** [vmiklos/ged2dot#3]
I get the following error when trying to convert my gedcom file:

```./ged2dot.py
Traceback (most recent call last):
  File "./ged2dot.py", line 790, in <module>
    main()
  File "./ged2dot.py", line 787, in main
    model.save(sys.stdout)
  File "./ged2dot.py", line 230, in save
    layout.calc()
  File "./ged2dot.py", line 606, in calc
    self.__addSiblingChildren(f)
  File "./ged2dot.py", line 552, in __addSiblingChildren
    lastChild = prevParent.fams.chil[-1]
AttributeError: 'NoneType' object has no attribute 'chil'```

**Comment by vmiklos** [comment]
Can you create a minimal reproducer that contains no sensitive data and still shows your problem? That would be necessary, unless you plan to provide a patch for the issue as well. :-)

**Comment by furlongm** [comment]
Tried to create a minimal reproducer but have not succeeded. I sent my ged privately via email. Let me know if it didn't go through.

**Comment by vmiklos** [comment]
Got it, thanks. I'll try to create a minimal anonymous one from it that still shows the problem -- otherwise could not add a test-case later.

**Comment by furlongm** [comment]
Great, let me know if you need any more information.

**Comment by vmiklos** [comment]
Please pull and test again, works for me now. There are a few unexpected nodes in the output, though. If you're interested, feel free to provide a patch that fixes those as well, or just generate the DOT output and edit out those manually. Or if you're a visual type, maybe generate the SVG as well, and edit out using an SVG editor. :-)

**Comment by furlongm** [comment]
What do you mean by unexpected nodes in the output?

There seems to be more missing subgraphs now, along with unconnected nodes that should be connected, and extra nodes named like e.g. I61Connect and I61.

**Comment by vmiklos** [comment]
If the ID of the node (like XYZConnect) shows up, that's not ideal, so I meant that, yes. :-)

**Comment by furlongm** [comment]
Should I open a new issue for those? It looks like lots of children are missing too.

**Comment by vmiklos** [comment]
You can, but pull requests are preferred over opening issues, this is easy Python after all, nothing too complex. I'm happy to teach people how to fish, less happy to spend much time giving people fish. ;-) If you have a specific question, I'm happy to answer.
