### ISSUE TITLE
__main__.NoSuchFamilyException: Can't find family 'F1' in the input file.

### ISSUE THREAD

**Issue by dmd** [vmiklos/ged2dot#6]

**Comment by vmiklos** [comment]
Please provide a reproducer GEDCOM file.

**Comment by dmd** [comment]
[export-Forest.ged.zip](https://github.com/vmiklos/ged2dot/files/737247/export-Forest.ged.zip)

**Comment by vmiklos** [comment]
Sorry, for some reason I missed your reply...

So the error message just says to you that there is no "F1" family in the GEDCOM file, which is by default considered to be the central family in the gedcom output. In your sample e.g. F6000000052439790907 is a valid family identifier. It's up to you to decide who should be the central family. (By default children from that family and various ancestors are shown in the dot output.) You can change "F1" to anything else in your ged2dotrc, in the rootFamily key.

**Comment by vmiklos** [comment]
Nothing actionable here in almost 2 years, closing.
