### ISSUE TITLE
RC file is ignored

### ISSUE THREAD

**Issue by rgerkin** [vmiklos/ged2dot#8]
If I change the rootFamily in the ged2dotrc file to `F5`, it is ignored and `F1` is still used as the root.  My current workaround is to just hardcode `self.rootFamily = 'F5'` into the code after the `parse()` method is run.  Alternatively, what is the command line syntax for this?

**Comment by rgerkin** [comment]
Nevermind, I see that the Makefile ignores it but running the script directly does not.

**Comment by vmiklos** [comment]
Ah good, I wondered what's wrong, given this option is something I do use. :-)
